/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrollmentNoRouteImport } from './routes/enrollment-no'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CentersRouteImport } from './routes/centers'
import { Route as CenterRouteImport } from './routes/center'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdmissionDeskRouteImport } from './routes/admission-desk'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentNoRoute = EnrollmentNoRouteImport.update({
  id: '/enrollment-no',
  path: '/enrollment-no',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CentersRoute = CentersRouteImport.update({
  id: '/centers',
  path: '/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionDeskRoute = AdmissionDeskRouteImport.update({
  id: '/admission-desk',
  path: '/admission-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admission-desk': typeof AdmissionDeskRoute
  '/approvals': typeof ApprovalsRoute
  '/boards': typeof BoardsRoute
  '/center': typeof CenterRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/enquiries': typeof EnquiriesRoute
  '/enrollment-no': typeof EnrollmentNoRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admission-desk': typeof AdmissionDeskRoute
  '/approvals': typeof ApprovalsRoute
  '/boards': typeof BoardsRoute
  '/center': typeof CenterRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/enquiries': typeof EnquiriesRoute
  '/enrollment-no': typeof EnrollmentNoRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admission-desk': typeof AdmissionDeskRoute
  '/approvals': typeof ApprovalsRoute
  '/boards': typeof BoardsRoute
  '/center': typeof CenterRoute
  '/centers': typeof CentersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/enquiries': typeof EnquiriesRoute
  '/enrollment-no': typeof EnrollmentNoRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admission-desk'
    | '/approvals'
    | '/boards'
    | '/center'
    | '/centers'
    | '/contact'
    | '/dashboard'
    | '/employees'
    | '/enquiries'
    | '/enrollment-no'
    | '/login'
    | '/programs'
    | '/signup'
    | '/staff'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admission-desk'
    | '/approvals'
    | '/boards'
    | '/center'
    | '/centers'
    | '/contact'
    | '/dashboard'
    | '/employees'
    | '/enquiries'
    | '/enrollment-no'
    | '/login'
    | '/programs'
    | '/signup'
    | '/staff'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admission-desk'
    | '/approvals'
    | '/boards'
    | '/center'
    | '/centers'
    | '/contact'
    | '/dashboard'
    | '/employees'
    | '/enquiries'
    | '/enrollment-no'
    | '/login'
    | '/programs'
    | '/signup'
    | '/staff'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdmissionDeskRoute: typeof AdmissionDeskRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BoardsRoute: typeof BoardsRoute
  CenterRoute: typeof CenterRoute
  CentersRoute: typeof CentersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  EnquiriesRoute: typeof EnquiriesRoute
  EnrollmentNoRoute: typeof EnrollmentNoRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment-no': {
      id: '/enrollment-no'
      path: '/enrollment-no'
      fullPath: '/enrollment-no'
      preLoaderRoute: typeof EnrollmentNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centers': {
      id: '/centers'
      path: '/centers'
      fullPath: '/centers'
      preLoaderRoute: typeof CentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-desk': {
      id: '/admission-desk'
      path: '/admission-desk'
      fullPath: '/admission-desk'
      preLoaderRoute: typeof AdmissionDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdmissionDeskRoute: AdmissionDeskRoute,
  ApprovalsRoute: ApprovalsRoute,
  BoardsRoute: BoardsRoute,
  CenterRoute: CenterRoute,
  CentersRoute: CentersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  EnquiriesRoute: EnquiriesRoute,
  EnrollmentNoRoute: EnrollmentNoRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
