
ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS enrollment_number text,
  ADD COLUMN IF NOT EXISTS admission_session text,
  ADD COLUMN IF NOT EXISTS study_mode text,
  ADD COLUMN IF NOT EXISTS course_name text,
  ADD COLUMN IF NOT EXISTS course_code text,
  ADD COLUMN IF NOT EXISTS medium_of_instruction text,
  ADD COLUMN IF NOT EXISTS duration_years numeric,
  ADD COLUMN IF NOT EXISTS current_semester integer,
  ADD COLUMN IF NOT EXISTS total_semesters integer,
  ADD COLUMN IF NOT EXISTS total_fee numeric,
  ADD COLUMN IF NOT EXISTS fee_paid numeric,
  ADD COLUMN IF NOT EXISTS fee_pending numeric,
  ADD COLUMN IF NOT EXISTS payment_status text,
  ADD COLUMN IF NOT EXISTS payment_mode text,
  ADD COLUMN IF NOT EXISTS last_payment_date date,
  ADD COLUMN IF NOT EXISTS next_due_date date,
  ADD COLUMN IF NOT EXISTS counsellor_name text,
  ADD COLUMN IF NOT EXISTS lead_source text,
  ADD COLUMN IF NOT EXISTS referral_name text,
  ADD COLUMN IF NOT EXISTS doc_photo boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_signature boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_id_proof boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_marksheet_10 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_marksheet_12 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_marksheet_degree boolean DEFAULT false;
